<a href="https://colab.research.google.com/github/2303A52139/AIML_2303a52139/blob/main/LAB_EXAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

# Load necessary libraries
import pandas as pd

# Load the dataset
data = pd.read_csv('/content/individual+household+electric+power+consumption.zip', sep=';', parse_dates=[[0, 1]], na_values='?',
                   infer_datetime_format=True, low_memory=False)

# Rename columns for easier access
data.columns = ['Datetime', 'Global_active_power', 'Global_reactive_power', 'Voltage',
                'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3']

# Convert columns to numeric where applicable
for col in data.columns[1:]:
    data[col] = pd.to_numeric(data[col], errors='coerce')

# Drop rows with NaN values
data.dropna(inplace=True)

# Find top 5 correlations
correlations = data.corr()['Global_active_power'].sort_values(ascending=False).drop('Global_active_power').head(5)
print("Top 5 reasons for electricity consumption:")
print(correlations)

<ipython-input-3-e88e75e54f46>:5: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  data = pd.read_csv('/content/individual+household+electric+power+consumption.zip', sep=';', parse_dates=[[0, 1]], na_values='?',
<ipython-input-3-e88e75e54f46>:5: FutureWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  data = pd.read_csv('/content/individual+household+electric+power+consumption.zip', sep=';', parse_dates=[[0, 1]], na_values='?',
<ipython-input-3-e88e75e54f46>:5: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data = pd.read_csv('/content/individ

Top 5 reasons for electricity consumption:
Global_intensity         0.998889
Sub_metering_3           0.638555
Sub_metering_1           0.484401
Sub_metering_2           0.434569
Global_reactive_power    0.247017
Name: Global_active_power, dtype: float64


In [5]:

# Find the row with the maximum Global_active_power
highest_consumption = data.loc[data['Global_active_power'].idxmax()]
print(f"\nDate and Time of highest consumption: {highest_consumption['Datetime']}")


Date and Time of highest consumption: 2009-02-22 17:09:00


In [6]:

# Find max and min values of Global_active_power
max_consumption = data['Global_active_power'].max()
min_consumption = data['Global_active_power'].min()

print(f"\nMax Consumption: {max_consumption} kW")
print(f"Min Consumption: {min_consumption} kW")


Max Consumption: 11.122 kW
Min Consumption: 0.076 kW


In [7]:

# Sum up the values for each sub-metering system
sub_metering_totals = {
    "Sub_metering_1": data['Sub_metering_1'].sum(),
    "Sub_metering_2": data['Sub_metering_2'].sum(),
    "Sub_metering_3": data['Sub_metering_3'].sum(),
}
highest_sub_metering = max(sub_metering_totals, key=sub_metering_totals.get)
print(f"\nHighest sub-metering system: {highest_sub_metering}")



Highest sub-metering system: Sub_metering_3


In [8]:

# Count unique values of Global_active_power
consumption_counts = data['Global_active_power'].value_counts()
print(f"\nConsumption counts of global electricity values:\n{consumption_counts}")


Consumption counts of global electricity values:
Global_active_power
0.218    9565
0.216    9363
0.322    9350
0.324    9304
0.326    9187
         ... 
7.094       1
7.930       1
8.274       1
8.246       1
8.600       1
Name: count, Length: 4186, dtype: int64


In [9]:

from sklearn.cluster import KMeans
import numpy as np

# Select features for clustering
features = data[['Global_active_power', 'Global_reactive_power', 'Voltage', 'Global_intensity']]

# Normalize the data
features_normalized = (features - features.mean()) / features.std()

# Apply KMeans
kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(features_normalized)

# Add cluster labels to the data
data['Cluster'] = kmeans.labels_

# Evaluate KMeans
print(f"\nKMeans Inertia: {kmeans.inertia_}")
print(f"Cluster Centers:\n{kmeans.cluster_centers_}")


KMeans Inertia: 4234209.466853724
Cluster Centers:
[[ 1.82930505  0.34037897 -0.9788808   1.83771747]
 [-0.13828124  1.11576541  0.03107028 -0.11660041]
 [-0.40824389 -0.56279523  0.23676287 -0.41963909]]
